// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orderer/hotstuff/configuration.proto

package hotstuff

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ConfigMetadata is serialized and set as the value of ConsensusType.Metadata in
// a channel configuration when the ConsensusType.Type is set "hotstuff".
type ConfigMetadata struct {
	Consenters           []*Consenter `protobuf:"bytes,1,rep,name=consenters,proto3" json:"consenters,omitempty"`
	Options              *Options     `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ConfigMetadata) Reset()         { *m = ConfigMetadata{} }
func (m *ConfigMetadata) String() string { return proto.CompactTextString(m) }
func (*ConfigMetadata) ProtoMessage()    {}
func (*ConfigMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e1f9c5da6505029, []int{0}
}

func (m *ConfigMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigMetadata.Unmarshal(m, b)
}
func (m *ConfigMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigMetadata.Marshal(b, m, deterministic)
}
func (m *ConfigMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigMetadata.Merge(m, src)
}
func (m *ConfigMetadata) XXX_Size() int {
	return xxx_messageInfo_ConfigMetadata.Size(m)
}
func (m *ConfigMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigMetadata proto.InternalMessageInfo

func (m *ConfigMetadata) GetConsenters() []*Consenter {
	if m != nil {
		return m.Consenters
	}
	return nil
}

func (m *ConfigMetadata) GetOptions() *Options {
	if m != nil {
		return m.Options
	}
	return nil
}

// Consenter represents a consenting node (i.e. replica).
type Consenter struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	ClientTlsCert        []byte   `protobuf:"bytes,3,opt,name=client_tls_cert,json=clientTlsCert,proto3" json:"client_tls_cert,omitempty"`
	ServerTlsCert        []byte   `protobuf:"bytes,4,opt,name=server_tls_cert,json=serverTlsCert,proto3" json:"server_tls_cert,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Consenter) Reset()         { *m = Consenter{} }
func (m *Consenter) String() string { return proto.CompactTextString(m) }
func (*Consenter) ProtoMessage()    {}
func (*Consenter) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e1f9c5da6505029, []int{1}
}

func (m *Consenter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consenter.Unmarshal(m, b)
}
func (m *Consenter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consenter.Marshal(b, m, deterministic)
}
func (m *Consenter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consenter.Merge(m, src)
}
func (m *Consenter) XXX_Size() int {
	return xxx_messageInfo_Consenter.Size(m)
}
func (m *Consenter) XXX_DiscardUnknown() {
	xxx_messageInfo_Consenter.DiscardUnknown(m)
}

var xxx_messageInfo_Consenter proto.InternalMessageInfo

func (m *Consenter) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Consenter) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Consenter) GetClientTlsCert() []byte {
	if m != nil {
		return m.ClientTlsCert
	}
	return nil
}

func (m *Consenter) GetServerTlsCert() []byte {
	if m != nil {
		return m.ServerTlsCert
	}
	return nil
}

// Defines the hotstuff parameters when 'hotstuff' is specified as the 'OrdererType'
type Options struct {
	// Number of peers
	N uint64 `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	// Fault tolerance
	F uint64 `protobuf:"varint,2,opt,name=f,proto3" json:"f,omitempty"`
	// Timeout of requests (seconds)
	RequestTimeoutNsec   uint64   `protobuf:"varint,3,opt,name=request_timeout_nsec,json=requestTimeoutNsec,proto3" json:"request_timeout_nsec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Options) Reset()         { *m = Options{} }
func (m *Options) String() string { return proto.CompactTextString(m) }
func (*Options) ProtoMessage()    {}
func (*Options) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e1f9c5da6505029, []int{2}
}

func (m *Options) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Options.Unmarshal(m, b)
}
func (m *Options) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Options.Marshal(b, m, deterministic)
}
func (m *Options) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Options.Merge(m, src)
}
func (m *Options) XXX_Size() int {
	return xxx_messageInfo_Options.Size(m)
}
func (m *Options) XXX_DiscardUnknown() {
	xxx_messageInfo_Options.DiscardUnknown(m)
}

var xxx_messageInfo_Options proto.InternalMessageInfo

func (m *Options) GetN() uint64 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *Options) GetF() uint64 {
	if m != nil {
		return m.F
	}
	return 0
}

func (m *Options) GetRequestTimeoutNsec() uint64 {
	if m != nil {
		return m.RequestTimeoutNsec
	}
	return 0
}

func init() {
	proto.RegisterType((*ConfigMetadata)(nil), "hotstuff.ConfigMetadata")
	proto.RegisterType((*Consenter)(nil), "hotstuff.Consenter")
	proto.RegisterType((*Options)(nil), "hotstuff.Options")
}

func init() {
	proto.RegisterFile("orderer/hotstuff/configuration.proto", fileDescriptor_4e1f9c5da6505029)
}

var fileDescriptor_4e1f9c5da6505029 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x4f, 0x8b, 0xdb, 0x30,
	0x10, 0xc5, 0x51, 0x63, 0x9a, 0x46, 0x49, 0x5a, 0xaa, 0xf6, 0xe0, 0xa3, 0x09, 0xa5, 0x18, 0x4a,
	0xe4, 0x92, 0x5c, 0x7a, 0x6e, 0xce, 0xed, 0x82, 0x08, 0x2c, 0xec, 0xc5, 0x38, 0xca, 0xf8, 0xcf,
	0xe2, 0x48, 0xde, 0xd1, 0x78, 0x61, 0xcf, 0xfb, 0xc5, 0x97, 0x48, 0x76, 0x12, 0xf6, 0x36, 0x9a,
	0xf7, 0x7b, 0xf3, 0xc4, 0x0c, 0xff, 0x61, 0xf1, 0x08, 0x08, 0x98, 0xd5, 0x96, 0x1c, 0xf5, 0x65,
	0x99, 0x69, 0x6b, 0xca, 0xa6, 0xea, 0xb1, 0xa0, 0xc6, 0x1a, 0xd9, 0xa1, 0x25, 0x2b, 0x3e, 0x8d,
	0xea, 0x0a, 0xf9, 0xe7, 0x9d, 0x07, 0xfe, 0x01, 0x15, 0xc7, 0x82, 0x0a, 0xb1, 0xe5, 0x5c, 0x5b,
	0xe3, 0xc0, 0x10, 0xa0, 0x8b, 0x59, 0x32, 0x49, 0xe7, 0x9b, 0x6f, 0x72, 0x34, 0xc8, 0xdd, 0xa8,
	0xa9, 0x1b, 0x4c, 0xfc, 0xe2, 0x53, 0xdb, 0x9d, 0x03, 0x5c, 0xfc, 0x21, 0x61, 0xe9, 0x7c, 0xf3,
	0xf5, 0xea, 0xb8, 0x0b, 0x82, 0x1a, 0x89, 0xd5, 0x2b, 0xe3, 0xb3, 0xcb, 0x18, 0x21, 0x78, 0x54,
	0x5b, 0x47, 0x31, 0x4b, 0x58, 0x3a, 0x53, 0xbe, 0x3e, 0xf7, 0x3a, 0x8b, 0xe4, 0x67, 0x2d, 0x95,
	0xaf, 0xc5, 0x4f, 0xfe, 0x45, 0xb7, 0x0d, 0x18, 0xca, 0xa9, 0x75, 0xb9, 0x06, 0xa4, 0x78, 0x92,
	0xb0, 0x74, 0xa1, 0x96, 0xa1, 0xbd, 0x6f, 0xdd, 0x0e, 0x02, 0xe7, 0x00, 0x9f, 0x01, 0xaf, 0x5c,
	0x14, 0xb8, 0xd0, 0x1e, 0xb8, 0xd5, 0x3d, 0x9f, 0x0e, 0x3f, 0x13, 0x0b, 0xce, 0x8c, 0xcf, 0x8f,
	0x14, 0x33, 0xe7, 0x57, 0xe9, 0x93, 0x23, 0xc5, 0x4a, 0xf1, 0x9b, 0x7f, 0x47, 0x78, 0xea, 0xc1,
	0x51, 0x4e, 0xcd, 0x09, 0x6c, 0x4f, 0xb9, 0x71, 0xa0, 0x7d, 0x76, 0xa4, 0xc4, 0xa0, 0xed, 0x83,
	0xf4, 0xdf, 0x81, 0xfe, 0xfb, 0xc8, 0xa5, 0xc5, 0x4a, 0xd6, 0x2f, 0x1d, 0x60, 0x0b, 0xc7, 0x0a,
	0x50, 0x96, 0xc5, 0x01, 0x1b, 0x1d, 0x96, 0xef, 0xe4, 0x70, 0xa2, 0xcb, 0x86, 0x1e, 0xfe, 0x54,
	0x0d, 0xd5, 0xfd, 0x41, 0x6a, 0x7b, 0xca, 0x6e, 0x6c, 0x59, 0xb0, 0xad, 0x83, 0x6d, 0x5d, 0xd9,
	0xec, 0xfd, 0x71, 0x0f, 0x1f, 0xbd, 0xb6, 0x7d, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xf9, 0xd7, 0x2a,
	0xb6, 0xf7, 0x01, 0x00, 0x00,
}
