// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orderer/sbft/configuration.proto

package sbft

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ConfigMetadata is serialized and set as the value of ConsensusType.Metadata in
// a channel configuration when the ConsensusType.Type is set "sbft".
type ConfigMetadata struct {
	Consenters           []*Consenter `protobuf:"bytes,1,rep,name=consenters,proto3" json:"consenters,omitempty"`
	Options              *Options     `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ConfigMetadata) Reset()         { *m = ConfigMetadata{} }
func (m *ConfigMetadata) String() string { return proto.CompactTextString(m) }
func (*ConfigMetadata) ProtoMessage()    {}
func (*ConfigMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_a145a2c703a577fa, []int{0}
}

func (m *ConfigMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigMetadata.Unmarshal(m, b)
}
func (m *ConfigMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigMetadata.Marshal(b, m, deterministic)
}
func (m *ConfigMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigMetadata.Merge(m, src)
}
func (m *ConfigMetadata) XXX_Size() int {
	return xxx_messageInfo_ConfigMetadata.Size(m)
}
func (m *ConfigMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigMetadata proto.InternalMessageInfo

func (m *ConfigMetadata) GetConsenters() []*Consenter {
	if m != nil {
		return m.Consenters
	}
	return nil
}

func (m *ConfigMetadata) GetOptions() *Options {
	if m != nil {
		return m.Options
	}
	return nil
}

// Consenter represents a consenting node (i.e. replica).
type Consenter struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	ClientSignCert       []byte   `protobuf:"bytes,3,opt,name=client_sign_cert,json=clientSignCert,proto3" json:"client_sign_cert,omitempty"`
	ServerTlsCert        []byte   `protobuf:"bytes,4,opt,name=server_tls_cert,json=serverTlsCert,proto3" json:"server_tls_cert,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Consenter) Reset()         { *m = Consenter{} }
func (m *Consenter) String() string { return proto.CompactTextString(m) }
func (*Consenter) ProtoMessage()    {}
func (*Consenter) Descriptor() ([]byte, []int) {
	return fileDescriptor_a145a2c703a577fa, []int{1}
}

func (m *Consenter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consenter.Unmarshal(m, b)
}
func (m *Consenter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consenter.Marshal(b, m, deterministic)
}
func (m *Consenter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consenter.Merge(m, src)
}
func (m *Consenter) XXX_Size() int {
	return xxx_messageInfo_Consenter.Size(m)
}
func (m *Consenter) XXX_DiscardUnknown() {
	xxx_messageInfo_Consenter.DiscardUnknown(m)
}

var xxx_messageInfo_Consenter proto.InternalMessageInfo

func (m *Consenter) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Consenter) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Consenter) GetClientSignCert() []byte {
	if m != nil {
		return m.ClientSignCert
	}
	return nil
}

func (m *Consenter) GetServerTlsCert() []byte {
	if m != nil {
		return m.ServerTlsCert
	}
	return nil
}

// Defines the SBFT parameters when 'sbft' is specified as the 'OrdererType'
type Options struct {
	N                    uint64   `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	F                    uint64   `protobuf:"varint,2,opt,name=f,proto3" json:"f,omitempty"`
	RequestTimeoutNsec   uint64   `protobuf:"varint,3,opt,name=request_timeout_nsec,json=requestTimeoutNsec,proto3" json:"request_timeout_nsec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Options) Reset()         { *m = Options{} }
func (m *Options) String() string { return proto.CompactTextString(m) }
func (*Options) ProtoMessage()    {}
func (*Options) Descriptor() ([]byte, []int) {
	return fileDescriptor_a145a2c703a577fa, []int{2}
}

func (m *Options) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Options.Unmarshal(m, b)
}
func (m *Options) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Options.Marshal(b, m, deterministic)
}
func (m *Options) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Options.Merge(m, src)
}
func (m *Options) XXX_Size() int {
	return xxx_messageInfo_Options.Size(m)
}
func (m *Options) XXX_DiscardUnknown() {
	xxx_messageInfo_Options.DiscardUnknown(m)
}

var xxx_messageInfo_Options proto.InternalMessageInfo

func (m *Options) GetN() uint64 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *Options) GetF() uint64 {
	if m != nil {
		return m.F
	}
	return 0
}

func (m *Options) GetRequestTimeoutNsec() uint64 {
	if m != nil {
		return m.RequestTimeoutNsec
	}
	return 0
}

type ConsensusConfig struct {
	Consensus            *Options              `protobuf:"bytes,1,opt,name=consensus,proto3" json:"consensus,omitempty"`
	Peers                map[string]*Consenter `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ConsensusConfig) Reset()         { *m = ConsensusConfig{} }
func (m *ConsensusConfig) String() string { return proto.CompactTextString(m) }
func (*ConsensusConfig) ProtoMessage()    {}
func (*ConsensusConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_a145a2c703a577fa, []int{3}
}

func (m *ConsensusConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsensusConfig.Unmarshal(m, b)
}
func (m *ConsensusConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsensusConfig.Marshal(b, m, deterministic)
}
func (m *ConsensusConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusConfig.Merge(m, src)
}
func (m *ConsensusConfig) XXX_Size() int {
	return xxx_messageInfo_ConsensusConfig.Size(m)
}
func (m *ConsensusConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusConfig proto.InternalMessageInfo

func (m *ConsensusConfig) GetConsensus() *Options {
	if m != nil {
		return m.Consensus
	}
	return nil
}

func (m *ConsensusConfig) GetPeers() map[string]*Consenter {
	if m != nil {
		return m.Peers
	}
	return nil
}

type JsonConfig struct {
	Consensus            *Options `protobuf:"bytes,1,opt,name=consensus,proto3" json:"consensus,omitempty"`
	Peers                []*Peer  `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JsonConfig) Reset()         { *m = JsonConfig{} }
func (m *JsonConfig) String() string { return proto.CompactTextString(m) }
func (*JsonConfig) ProtoMessage()    {}
func (*JsonConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_a145a2c703a577fa, []int{4}
}

func (m *JsonConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JsonConfig.Unmarshal(m, b)
}
func (m *JsonConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JsonConfig.Marshal(b, m, deterministic)
}
func (m *JsonConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JsonConfig.Merge(m, src)
}
func (m *JsonConfig) XXX_Size() int {
	return xxx_messageInfo_JsonConfig.Size(m)
}
func (m *JsonConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_JsonConfig.DiscardUnknown(m)
}

var xxx_messageInfo_JsonConfig proto.InternalMessageInfo

func (m *JsonConfig) GetConsensus() *Options {
	if m != nil {
		return m.Consensus
	}
	return nil
}

func (m *JsonConfig) GetPeers() []*Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

type Peer struct {
	Address              string     `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Cert                 *Consenter `protobuf:"bytes,2,opt,name=cert,proto3" json:"cert,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Peer) Reset()         { *m = Peer{} }
func (m *Peer) String() string { return proto.CompactTextString(m) }
func (*Peer) ProtoMessage()    {}
func (*Peer) Descriptor() ([]byte, []int) {
	return fileDescriptor_a145a2c703a577fa, []int{5}
}

func (m *Peer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Peer.Unmarshal(m, b)
}
func (m *Peer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Peer.Marshal(b, m, deterministic)
}
func (m *Peer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Peer.Merge(m, src)
}
func (m *Peer) XXX_Size() int {
	return xxx_messageInfo_Peer.Size(m)
}
func (m *Peer) XXX_DiscardUnknown() {
	xxx_messageInfo_Peer.DiscardUnknown(m)
}

var xxx_messageInfo_Peer proto.InternalMessageInfo

func (m *Peer) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Peer) GetCert() *Consenter {
	if m != nil {
		return m.Cert
	}
	return nil
}

func init() {
	proto.RegisterType((*ConfigMetadata)(nil), "sbft.ConfigMetadata")
	proto.RegisterType((*Consenter)(nil), "sbft.Consenter")
	proto.RegisterType((*Options)(nil), "sbft.Options")
	proto.RegisterType((*ConsensusConfig)(nil), "sbft.consensus_config")
	proto.RegisterMapType((map[string]*Consenter)(nil), "sbft.consensus_config.PeersEntry")
	proto.RegisterType((*JsonConfig)(nil), "sbft.json_config")
	proto.RegisterType((*Peer)(nil), "sbft.peer")
}

func init() { proto.RegisterFile("orderer/sbft/configuration.proto", fileDescriptor_a145a2c703a577fa) }

var fileDescriptor_a145a2c703a577fa = []byte{
	// 461 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x5d, 0x6b, 0xd4, 0x40,
	0x14, 0x65, 0x76, 0x53, 0x97, 0xbd, 0xdb, 0x6d, 0x97, 0xc1, 0x87, 0xe0, 0x53, 0x8c, 0xa8, 0x41,
	0x69, 0x22, 0x55, 0x50, 0x7c, 0x74, 0xe9, 0x83, 0x0f, 0x7e, 0x10, 0x0b, 0x82, 0x08, 0x21, 0x1f,
	0x37, 0xd9, 0xd4, 0x74, 0x26, 0xce, 0x9d, 0x14, 0xf6, 0x07, 0xf8, 0xcb, 0xfc, 0x63, 0x32, 0x33,
	0xd9, 0x76, 0xb5, 0xf8, 0xd2, 0xb7, 0x9b, 0x73, 0xce, 0xbd, 0xf7, 0x70, 0xee, 0x04, 0x02, 0xa9,
	0x2a, 0x54, 0xa8, 0x12, 0x2a, 0x6a, 0x9d, 0x94, 0x52, 0xd4, 0x6d, 0x33, 0xa8, 0x5c, 0xb7, 0x52,
	0xc4, 0xbd, 0x92, 0x5a, 0x72, 0xcf, 0x30, 0xe1, 0x05, 0x1c, 0xad, 0x2d, 0xf9, 0x01, 0x75, 0x5e,
	0xe5, 0x3a, 0xe7, 0x09, 0x40, 0x29, 0x05, 0xa1, 0xd0, 0xa8, 0xc8, 0x67, 0xc1, 0x34, 0x5a, 0x9c,
	0x1e, 0xc7, 0x46, 0x1c, 0xaf, 0x77, 0x78, 0xba, 0x27, 0xe1, 0x4f, 0x61, 0x26, 0x7b, 0x33, 0x98,
	0xfc, 0x49, 0xc0, 0xa2, 0xc5, 0xe9, 0xd2, 0xa9, 0x3f, 0x39, 0x30, 0xdd, 0xb1, 0xe1, 0x2f, 0x06,
	0xf3, 0xeb, 0x11, 0x9c, 0x83, 0xb7, 0x91, 0xa4, 0x7d, 0x16, 0xb0, 0x68, 0x9e, 0xda, 0xda, 0x60,
	0xbd, 0x54, 0xda, 0xce, 0x59, 0xa6, 0xb6, 0xe6, 0x11, 0xac, 0xca, 0xae, 0x45, 0xa1, 0x33, 0x6a,
	0x1b, 0x91, 0x95, 0xa8, 0xb4, 0x3f, 0x0d, 0x58, 0x74, 0x98, 0x1e, 0x39, 0xfc, 0x4b, 0xdb, 0x88,
	0x35, 0x2a, 0xcd, 0x9f, 0xc0, 0x31, 0xa1, 0xba, 0x42, 0x95, 0xe9, 0x8e, 0x9c, 0xd0, 0xb3, 0xc2,
	0xa5, 0x83, 0xcf, 0x3b, 0x32, 0xba, 0xf0, 0x2b, 0xcc, 0x46, 0x6f, 0xfc, 0x10, 0x98, 0xb0, 0x0e,
	0xbc, 0x94, 0x09, 0xf3, 0x55, 0xdb, 0xdd, 0x5e, 0xca, 0x6a, 0xfe, 0x02, 0xee, 0x2b, 0xfc, 0x39,
	0x20, 0xe9, 0x4c, 0xb7, 0x97, 0x28, 0x07, 0x9d, 0x09, 0xc2, 0xd2, 0x2e, 0xf7, 0x52, 0x3e, 0x72,
	0xe7, 0x8e, 0xfa, 0x48, 0x58, 0x86, 0xbf, 0x19, 0xac, 0x5c, 0x30, 0x34, 0x50, 0xe6, 0x42, 0xe7,
	0xcf, 0x61, 0x7e, 0x8d, 0xd9, 0x55, 0xb7, 0x02, 0xba, 0xe1, 0xf9, 0x6b, 0x38, 0xe8, 0xd1, 0xe4,
	0x3e, 0xb1, 0xb9, 0x3f, 0x74, 0xc2, 0x7f, 0x67, 0xc6, 0x9f, 0x8d, 0xe6, 0x4c, 0x68, 0xb5, 0x4d,
	0x9d, 0xfe, 0xc1, 0x7b, 0x80, 0x1b, 0x90, 0xaf, 0x60, 0xfa, 0x03, 0xb7, 0x63, 0xb4, 0xa6, 0xe4,
	0x8f, 0xe1, 0xe0, 0x2a, 0xef, 0x06, 0x1c, 0x4f, 0x74, 0xeb, 0xa0, 0x8e, 0x7d, 0x3b, 0x79, 0xc3,
	0xc2, 0xef, 0xb0, 0xb8, 0x20, 0x29, 0xee, 0xe4, 0x3f, 0xf8, 0xdb, 0x3f, 0x38, 0xa1, 0x81, 0x46,
	0xa3, 0xe1, 0x19, 0x78, 0xa6, 0xe0, 0x3e, 0xcc, 0xf2, 0xaa, 0x52, 0x48, 0x34, 0xda, 0xdc, 0x7d,
	0xf2, 0x47, 0xe0, 0xd9, 0xdb, 0xfd, 0xc7, 0xa9, 0x25, 0xdf, 0x15, 0xf0, 0x4c, 0xaa, 0x26, 0xde,
	0x6c, 0x7b, 0x54, 0x1d, 0x56, 0x0d, 0xaa, 0xb8, 0xce, 0x0b, 0xd5, 0x96, 0xee, 0x75, 0x53, 0x3c,
	0xbe, 0x7f, 0xdb, 0xfd, 0xed, 0x55, 0xd3, 0xea, 0xcd, 0x50, 0xc4, 0xa5, 0xbc, 0x4c, 0xf6, 0x5a,
	0x12, 0xd7, 0x72, 0xe2, 0x5a, 0x4e, 0x1a, 0x99, 0xec, 0xff, 0x35, 0xc5, 0x3d, 0x8b, 0xbf, 0xfc,
	0x13, 0x00, 0x00, 0xff, 0xff, 0x2a, 0x80, 0x21, 0x55, 0x4c, 0x03, 0x00, 0x00,
}
