// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orderer/sbft/simplebft.proto

package sbft

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MultiChainMsg struct {
	ChainID              string   `protobuf:"bytes,1,opt,name=chainID,proto3" json:"chainID,omitempty"`
	Msg                  *Msg     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiChainMsg) Reset()         { *m = MultiChainMsg{} }
func (m *MultiChainMsg) String() string { return proto.CompactTextString(m) }
func (*MultiChainMsg) ProtoMessage()    {}
func (*MultiChainMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_579f0507be858662, []int{0}
}

func (m *MultiChainMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiChainMsg.Unmarshal(m, b)
}
func (m *MultiChainMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiChainMsg.Marshal(b, m, deterministic)
}
func (m *MultiChainMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiChainMsg.Merge(m, src)
}
func (m *MultiChainMsg) XXX_Size() int {
	return xxx_messageInfo_MultiChainMsg.Size(m)
}
func (m *MultiChainMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiChainMsg.DiscardUnknown(m)
}

var xxx_messageInfo_MultiChainMsg proto.InternalMessageInfo

func (m *MultiChainMsg) GetChainID() string {
	if m != nil {
		return m.ChainID
	}
	return ""
}

func (m *MultiChainMsg) GetMsg() *Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

type Msg struct {
	// Types that are valid to be assigned to Type:
	//	*Msg_Request
	//	*Msg_Preprepare
	//	*Msg_Prepare
	//	*Msg_Commit
	//	*Msg_ViewChange
	//	*Msg_NewView
	//	*Msg_Checkpoint
	//	*Msg_Hello
	Type                 isMsg_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_579f0507be858662, []int{1}
}

func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

type isMsg_Type interface {
	isMsg_Type()
}

type Msg_Request struct {
	Request *Request `protobuf:"bytes,1,opt,name=request,proto3,oneof"`
}

type Msg_Preprepare struct {
	Preprepare *Preprepare `protobuf:"bytes,2,opt,name=preprepare,proto3,oneof"`
}

type Msg_Prepare struct {
	Prepare *Subject `protobuf:"bytes,3,opt,name=prepare,proto3,oneof"`
}

type Msg_Commit struct {
	Commit *Subject `protobuf:"bytes,4,opt,name=commit,proto3,oneof"`
}

type Msg_ViewChange struct {
	ViewChange *Signed `protobuf:"bytes,5,opt,name=view_change,json=viewChange,proto3,oneof"`
}

type Msg_NewView struct {
	NewView *NewView `protobuf:"bytes,6,opt,name=new_view,json=newView,proto3,oneof"`
}

type Msg_Checkpoint struct {
	Checkpoint *Checkpoint `protobuf:"bytes,7,opt,name=checkpoint,proto3,oneof"`
}

type Msg_Hello struct {
	Hello *Hello `protobuf:"bytes,8,opt,name=hello,proto3,oneof"`
}

func (*Msg_Request) isMsg_Type() {}

func (*Msg_Preprepare) isMsg_Type() {}

func (*Msg_Prepare) isMsg_Type() {}

func (*Msg_Commit) isMsg_Type() {}

func (*Msg_ViewChange) isMsg_Type() {}

func (*Msg_NewView) isMsg_Type() {}

func (*Msg_Checkpoint) isMsg_Type() {}

func (*Msg_Hello) isMsg_Type() {}

func (m *Msg) GetType() isMsg_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Msg) GetRequest() *Request {
	if x, ok := m.GetType().(*Msg_Request); ok {
		return x.Request
	}
	return nil
}

func (m *Msg) GetPreprepare() *Preprepare {
	if x, ok := m.GetType().(*Msg_Preprepare); ok {
		return x.Preprepare
	}
	return nil
}

func (m *Msg) GetPrepare() *Subject {
	if x, ok := m.GetType().(*Msg_Prepare); ok {
		return x.Prepare
	}
	return nil
}

func (m *Msg) GetCommit() *Subject {
	if x, ok := m.GetType().(*Msg_Commit); ok {
		return x.Commit
	}
	return nil
}

func (m *Msg) GetViewChange() *Signed {
	if x, ok := m.GetType().(*Msg_ViewChange); ok {
		return x.ViewChange
	}
	return nil
}

func (m *Msg) GetNewView() *NewView {
	if x, ok := m.GetType().(*Msg_NewView); ok {
		return x.NewView
	}
	return nil
}

func (m *Msg) GetCheckpoint() *Checkpoint {
	if x, ok := m.GetType().(*Msg_Checkpoint); ok {
		return x.Checkpoint
	}
	return nil
}

func (m *Msg) GetHello() *Hello {
	if x, ok := m.GetType().(*Msg_Hello); ok {
		return x.Hello
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Msg) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Msg_Request)(nil),
		(*Msg_Preprepare)(nil),
		(*Msg_Prepare)(nil),
		(*Msg_Commit)(nil),
		(*Msg_ViewChange)(nil),
		(*Msg_NewView)(nil),
		(*Msg_Checkpoint)(nil),
		(*Msg_Hello)(nil),
	}
}

type Request struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_579f0507be858662, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type SeqView struct {
	View                 uint64   `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Seq                  uint64   `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SeqView) Reset()         { *m = SeqView{} }
func (m *SeqView) String() string { return proto.CompactTextString(m) }
func (*SeqView) ProtoMessage()    {}
func (*SeqView) Descriptor() ([]byte, []int) {
	return fileDescriptor_579f0507be858662, []int{3}
}

func (m *SeqView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeqView.Unmarshal(m, b)
}
func (m *SeqView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeqView.Marshal(b, m, deterministic)
}
func (m *SeqView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeqView.Merge(m, src)
}
func (m *SeqView) XXX_Size() int {
	return xxx_messageInfo_SeqView.Size(m)
}
func (m *SeqView) XXX_DiscardUnknown() {
	xxx_messageInfo_SeqView.DiscardUnknown(m)
}

var xxx_messageInfo_SeqView proto.InternalMessageInfo

func (m *SeqView) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *SeqView) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

type BatchHeader struct {
	Seq                  uint64   `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	PrevHash             []byte   `protobuf:"bytes,2,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	DataHash             []byte   `protobuf:"bytes,3,opt,name=data_hash,json=dataHash,proto3" json:"data_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatchHeader) Reset()         { *m = BatchHeader{} }
func (m *BatchHeader) String() string { return proto.CompactTextString(m) }
func (*BatchHeader) ProtoMessage()    {}
func (*BatchHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_579f0507be858662, []int{4}
}

func (m *BatchHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchHeader.Unmarshal(m, b)
}
func (m *BatchHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchHeader.Marshal(b, m, deterministic)
}
func (m *BatchHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchHeader.Merge(m, src)
}
func (m *BatchHeader) XXX_Size() int {
	return xxx_messageInfo_BatchHeader.Size(m)
}
func (m *BatchHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BatchHeader proto.InternalMessageInfo

func (m *BatchHeader) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *BatchHeader) GetPrevHash() []byte {
	if m != nil {
		return m.PrevHash
	}
	return nil
}

func (m *BatchHeader) GetDataHash() []byte {
	if m != nil {
		return m.DataHash
	}
	return nil
}

type Batch struct {
	Header               []byte            `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Payloads             [][]byte          `protobuf:"bytes,2,rep,name=payloads,proto3" json:"payloads,omitempty"`
	Signatures           map[uint64][]byte `protobuf:"bytes,3,rep,name=signatures,proto3" json:"signatures,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Batch) Reset()         { *m = Batch{} }
func (m *Batch) String() string { return proto.CompactTextString(m) }
func (*Batch) ProtoMessage()    {}
func (*Batch) Descriptor() ([]byte, []int) {
	return fileDescriptor_579f0507be858662, []int{5}
}

func (m *Batch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Batch.Unmarshal(m, b)
}
func (m *Batch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Batch.Marshal(b, m, deterministic)
}
func (m *Batch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Batch.Merge(m, src)
}
func (m *Batch) XXX_Size() int {
	return xxx_messageInfo_Batch.Size(m)
}
func (m *Batch) XXX_DiscardUnknown() {
	xxx_messageInfo_Batch.DiscardUnknown(m)
}

var xxx_messageInfo_Batch proto.InternalMessageInfo

func (m *Batch) GetHeader() []byte {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Batch) GetPayloads() [][]byte {
	if m != nil {
		return m.Payloads
	}
	return nil
}

func (m *Batch) GetSignatures() map[uint64][]byte {
	if m != nil {
		return m.Signatures
	}
	return nil
}

type Preprepare struct {
	Seq                  *SeqView `protobuf:"bytes,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Batch                *Batch   `protobuf:"bytes,2,opt,name=batch,proto3" json:"batch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Preprepare) Reset()         { *m = Preprepare{} }
func (m *Preprepare) String() string { return proto.CompactTextString(m) }
func (*Preprepare) ProtoMessage()    {}
func (*Preprepare) Descriptor() ([]byte, []int) {
	return fileDescriptor_579f0507be858662, []int{6}
}

func (m *Preprepare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Preprepare.Unmarshal(m, b)
}
func (m *Preprepare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Preprepare.Marshal(b, m, deterministic)
}
func (m *Preprepare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Preprepare.Merge(m, src)
}
func (m *Preprepare) XXX_Size() int {
	return xxx_messageInfo_Preprepare.Size(m)
}
func (m *Preprepare) XXX_DiscardUnknown() {
	xxx_messageInfo_Preprepare.DiscardUnknown(m)
}

var xxx_messageInfo_Preprepare proto.InternalMessageInfo

func (m *Preprepare) GetSeq() *SeqView {
	if m != nil {
		return m.Seq
	}
	return nil
}

func (m *Preprepare) GetBatch() *Batch {
	if m != nil {
		return m.Batch
	}
	return nil
}

type Subject struct {
	Seq                  *SeqView `protobuf:"bytes,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Digest               []byte   `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subject) Reset()         { *m = Subject{} }
func (m *Subject) String() string { return proto.CompactTextString(m) }
func (*Subject) ProtoMessage()    {}
func (*Subject) Descriptor() ([]byte, []int) {
	return fileDescriptor_579f0507be858662, []int{7}
}

func (m *Subject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subject.Unmarshal(m, b)
}
func (m *Subject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subject.Marshal(b, m, deterministic)
}
func (m *Subject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subject.Merge(m, src)
}
func (m *Subject) XXX_Size() int {
	return xxx_messageInfo_Subject.Size(m)
}
func (m *Subject) XXX_DiscardUnknown() {
	xxx_messageInfo_Subject.DiscardUnknown(m)
}

var xxx_messageInfo_Subject proto.InternalMessageInfo

func (m *Subject) GetSeq() *SeqView {
	if m != nil {
		return m.Seq
	}
	return nil
}

func (m *Subject) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

type ViewChange struct {
	View                 uint64     `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Pset                 []*Subject `protobuf:"bytes,2,rep,name=pset,proto3" json:"pset,omitempty"`
	Qset                 []*Subject `protobuf:"bytes,3,rep,name=qset,proto3" json:"qset,omitempty"`
	Checkpoint           *Batch     `protobuf:"bytes,4,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ViewChange) Reset()         { *m = ViewChange{} }
func (m *ViewChange) String() string { return proto.CompactTextString(m) }
func (*ViewChange) ProtoMessage()    {}
func (*ViewChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_579f0507be858662, []int{8}
}

func (m *ViewChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewChange.Unmarshal(m, b)
}
func (m *ViewChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewChange.Marshal(b, m, deterministic)
}
func (m *ViewChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewChange.Merge(m, src)
}
func (m *ViewChange) XXX_Size() int {
	return xxx_messageInfo_ViewChange.Size(m)
}
func (m *ViewChange) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewChange.DiscardUnknown(m)
}

var xxx_messageInfo_ViewChange proto.InternalMessageInfo

func (m *ViewChange) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *ViewChange) GetPset() []*Subject {
	if m != nil {
		return m.Pset
	}
	return nil
}

func (m *ViewChange) GetQset() []*Subject {
	if m != nil {
		return m.Qset
	}
	return nil
}

func (m *ViewChange) GetCheckpoint() *Batch {
	if m != nil {
		return m.Checkpoint
	}
	return nil
}

type Signed struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signed) Reset()         { *m = Signed{} }
func (m *Signed) String() string { return proto.CompactTextString(m) }
func (*Signed) ProtoMessage()    {}
func (*Signed) Descriptor() ([]byte, []int) {
	return fileDescriptor_579f0507be858662, []int{9}
}

func (m *Signed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signed.Unmarshal(m, b)
}
func (m *Signed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signed.Marshal(b, m, deterministic)
}
func (m *Signed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signed.Merge(m, src)
}
func (m *Signed) XXX_Size() int {
	return xxx_messageInfo_Signed.Size(m)
}
func (m *Signed) XXX_DiscardUnknown() {
	xxx_messageInfo_Signed.DiscardUnknown(m)
}

var xxx_messageInfo_Signed proto.InternalMessageInfo

func (m *Signed) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Signed) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type NewView struct {
	View                 uint64             `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Vset                 map[uint64]*Signed `protobuf:"bytes,2,rep,name=vset,proto3" json:"vset,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Xset                 *Subject           `protobuf:"bytes,3,opt,name=xset,proto3" json:"xset,omitempty"`
	Batch                *Batch             `protobuf:"bytes,4,opt,name=batch,proto3" json:"batch,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *NewView) Reset()         { *m = NewView{} }
func (m *NewView) String() string { return proto.CompactTextString(m) }
func (*NewView) ProtoMessage()    {}
func (*NewView) Descriptor() ([]byte, []int) {
	return fileDescriptor_579f0507be858662, []int{10}
}

func (m *NewView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewView.Unmarshal(m, b)
}
func (m *NewView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewView.Marshal(b, m, deterministic)
}
func (m *NewView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewView.Merge(m, src)
}
func (m *NewView) XXX_Size() int {
	return xxx_messageInfo_NewView.Size(m)
}
func (m *NewView) XXX_DiscardUnknown() {
	xxx_messageInfo_NewView.DiscardUnknown(m)
}

var xxx_messageInfo_NewView proto.InternalMessageInfo

func (m *NewView) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *NewView) GetVset() map[uint64]*Signed {
	if m != nil {
		return m.Vset
	}
	return nil
}

func (m *NewView) GetXset() *Subject {
	if m != nil {
		return m.Xset
	}
	return nil
}

func (m *NewView) GetBatch() *Batch {
	if m != nil {
		return m.Batch
	}
	return nil
}

type Checkpoint struct {
	Seq                  uint64   `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Digest               []byte   `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Checkpoint) Reset()         { *m = Checkpoint{} }
func (m *Checkpoint) String() string { return proto.CompactTextString(m) }
func (*Checkpoint) ProtoMessage()    {}
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_579f0507be858662, []int{11}
}

func (m *Checkpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Checkpoint.Unmarshal(m, b)
}
func (m *Checkpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Checkpoint.Marshal(b, m, deterministic)
}
func (m *Checkpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Checkpoint.Merge(m, src)
}
func (m *Checkpoint) XXX_Size() int {
	return xxx_messageInfo_Checkpoint.Size(m)
}
func (m *Checkpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Checkpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Checkpoint proto.InternalMessageInfo

func (m *Checkpoint) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Checkpoint) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

func (m *Checkpoint) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Hello struct {
	Batch                *Batch   `protobuf:"bytes,1,opt,name=batch,proto3" json:"batch,omitempty"`
	NewView              *NewView `protobuf:"bytes,2,opt,name=new_view,json=newView,proto3" json:"new_view,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hello) Reset()         { *m = Hello{} }
func (m *Hello) String() string { return proto.CompactTextString(m) }
func (*Hello) ProtoMessage()    {}
func (*Hello) Descriptor() ([]byte, []int) {
	return fileDescriptor_579f0507be858662, []int{12}
}

func (m *Hello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hello.Unmarshal(m, b)
}
func (m *Hello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hello.Marshal(b, m, deterministic)
}
func (m *Hello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hello.Merge(m, src)
}
func (m *Hello) XXX_Size() int {
	return xxx_messageInfo_Hello.Size(m)
}
func (m *Hello) XXX_DiscardUnknown() {
	xxx_messageInfo_Hello.DiscardUnknown(m)
}

var xxx_messageInfo_Hello proto.InternalMessageInfo

func (m *Hello) GetBatch() *Batch {
	if m != nil {
		return m.Batch
	}
	return nil
}

func (m *Hello) GetNewView() *NewView {
	if m != nil {
		return m.NewView
	}
	return nil
}

func init() {
	proto.RegisterType((*MultiChainMsg)(nil), "sbft.MultiChainMsg")
	proto.RegisterType((*Msg)(nil), "sbft.Msg")
	proto.RegisterType((*Request)(nil), "sbft.Request")
	proto.RegisterType((*SeqView)(nil), "sbft.SeqView")
	proto.RegisterType((*BatchHeader)(nil), "sbft.BatchHeader")
	proto.RegisterType((*Batch)(nil), "sbft.Batch")
	proto.RegisterMapType((map[uint64][]byte)(nil), "sbft.Batch.SignaturesEntry")
	proto.RegisterType((*Preprepare)(nil), "sbft.Preprepare")
	proto.RegisterType((*Subject)(nil), "sbft.Subject")
	proto.RegisterType((*ViewChange)(nil), "sbft.ViewChange")
	proto.RegisterType((*Signed)(nil), "sbft.Signed")
	proto.RegisterType((*NewView)(nil), "sbft.NewView")
	proto.RegisterMapType((map[uint64]*Signed)(nil), "sbft.NewView.VsetEntry")
	proto.RegisterType((*Checkpoint)(nil), "sbft.Checkpoint")
	proto.RegisterType((*Hello)(nil), "sbft.Hello")
}

func init() { proto.RegisterFile("orderer/sbft/simplebft.proto", fileDescriptor_579f0507be858662) }

var fileDescriptor_579f0507be858662 = []byte{
	// 758 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0xcd, 0x4e, 0xe3, 0x48,
	0x10, 0xc6, 0xb1, 0xf3, 0x57, 0x01, 0x2d, 0x6a, 0xad, 0x58, 0x0b, 0x90, 0x36, 0x98, 0xc3, 0x66,
	0x41, 0x38, 0x52, 0x76, 0x0f, 0x2b, 0x56, 0x7b, 0x09, 0xcb, 0x2a, 0x7b, 0x60, 0x84, 0x0c, 0x42,
	0x9a, 0xb9, 0x20, 0xdb, 0x29, 0x6c, 0x0f, 0x89, 0xed, 0xd8, 0x9d, 0x84, 0x3c, 0xc7, 0x3c, 0xcc,
	0x3c, 0xca, 0xbc, 0xc9, 0x9c, 0x47, 0xd5, 0xdd, 0x89, 0x4d, 0xc6, 0x68, 0x24, 0x1f, 0xba, 0xeb,
	0xfb, 0xaa, 0x54, 0x5f, 0xfd, 0xb4, 0xe1, 0x38, 0xc9, 0xc6, 0x98, 0x61, 0xd6, 0xcf, 0xbd, 0x27,
	0xde, 0xcf, 0xa3, 0x69, 0x3a, 0x41, 0xef, 0x89, 0xdb, 0x69, 0x96, 0xf0, 0x84, 0x19, 0x64, 0xb5,
	0xfe, 0x83, 0xbd, 0x9b, 0xf9, 0x84, 0x47, 0x57, 0xa1, 0x1b, 0xc5, 0x37, 0x79, 0xc0, 0x4c, 0x68,
	0xfa, 0x74, 0xfe, 0xff, 0x5f, 0x53, 0xeb, 0x6a, 0xbd, 0xb6, 0xb3, 0xbe, 0xb2, 0x23, 0xd0, 0xa7,
	0x79, 0x60, 0xd6, 0xba, 0x5a, 0xaf, 0x33, 0x68, 0xdb, 0xe4, 0x6e, 0xdf, 0xe4, 0x81, 0x43, 0x56,
	0xeb, 0x6b, 0x0d, 0x74, 0x72, 0xff, 0x1d, 0x9a, 0x19, 0xce, 0xe6, 0x98, 0x73, 0xe1, 0xde, 0x19,
	0xec, 0x49, 0xa2, 0x23, 0x8d, 0xa3, 0x1d, 0x67, 0x8d, 0xb3, 0x01, 0x40, 0x9a, 0x21, 0x7d, 0x6e,
	0x86, 0x2a, 0xec, 0xbe, 0x64, 0xdf, 0x6e, 0xec, 0xa3, 0x1d, 0xa7, 0xc4, 0xa2, 0xf0, 0x6b, 0x07,
	0xbd, 0x1c, 0xfe, 0x6e, 0xee, 0x7d, 0x44, 0x5f, 0x84, 0x5f, 0x53, 0x7f, 0x83, 0x86, 0x9f, 0x4c,
	0xa7, 0x11, 0x37, 0x8d, 0x6a, 0xa6, 0x82, 0x59, 0x1f, 0x3a, 0x8b, 0x08, 0x97, 0x8f, 0x7e, 0xe8,
	0xc6, 0x01, 0x9a, 0x75, 0xc1, 0xde, 0x55, 0xec, 0x28, 0x88, 0x71, 0x4c, 0x49, 0x10, 0xe5, 0x4a,
	0x30, 0xd8, 0x19, 0xb4, 0x62, 0x5c, 0x3e, 0x92, 0xc5, 0x6c, 0x94, 0x63, 0xbf, 0xc3, 0xe5, 0x43,
	0x84, 0x4b, 0xca, 0x22, 0x96, 0x47, 0x12, 0xe9, 0x87, 0xe8, 0x3f, 0xa7, 0x49, 0x14, 0x73, 0xb3,
	0x59, 0x16, 0x79, 0xb5, 0xb1, 0x53, 0xfc, 0x82, 0xc5, 0x4e, 0xa1, 0x1e, 0xe2, 0x64, 0x92, 0x98,
	0x2d, 0x41, 0xef, 0x48, 0xfa, 0x88, 0x4c, 0xa3, 0x1d, 0x47, 0x62, 0xc3, 0x06, 0x18, 0x7c, 0x95,
	0xa2, 0x75, 0x0a, 0x4d, 0x55, 0x5b, 0x6a, 0x5d, 0xea, 0xae, 0x26, 0x89, 0x3b, 0x16, 0xb5, 0xdf,
	0x75, 0xd6, 0x57, 0xab, 0x0f, 0xcd, 0x3b, 0x9c, 0x89, 0x84, 0x18, 0x18, 0x22, 0x71, 0x62, 0x18,
	0x8e, 0x38, 0xb3, 0x7d, 0xd0, 0x73, 0x9c, 0x89, 0x16, 0x18, 0x0e, 0x1d, 0xad, 0xf7, 0xd0, 0x19,
	0xba, 0xdc, 0x0f, 0x47, 0xe8, 0x8e, 0x31, 0x5b, 0x13, 0xb4, 0x0d, 0x81, 0x1d, 0x41, 0x3b, 0xcd,
	0x70, 0xf1, 0x18, 0xba, 0x79, 0x28, 0x1c, 0x77, 0x9d, 0x16, 0x19, 0x46, 0x6e, 0x1e, 0x12, 0x38,
	0x76, 0xb9, 0x2b, 0x41, 0x5d, 0x82, 0x64, 0x20, 0xd0, 0xfa, 0xac, 0x41, 0x5d, 0xc4, 0x66, 0x07,
	0xd0, 0x08, 0x45, 0x7c, 0x95, 0xae, 0xba, 0xb1, 0x43, 0x68, 0xa9, 0xc4, 0x73, 0xb3, 0xd6, 0xd5,
	0x45, 0x68, 0x75, 0x67, 0x7f, 0x03, 0xe4, 0x51, 0x10, 0xbb, 0x7c, 0x9e, 0x61, 0x6e, 0xea, 0x5d,
	0xbd, 0xd7, 0x19, 0x1c, 0xc9, 0x02, 0x89, 0xa0, 0xa2, 0x63, 0x12, 0xbd, 0x8e, 0x79, 0xb6, 0x72,
	0x4a, 0xf4, 0xc3, 0x7f, 0xe0, 0xa7, 0x2d, 0x98, 0x94, 0x3d, 0xe3, 0x6a, 0xad, 0xec, 0x19, 0x57,
	0xec, 0x67, 0xa8, 0x2f, 0xdc, 0xc9, 0x1c, 0x95, 0x2a, 0x79, 0xb9, 0xac, 0xfd, 0xa5, 0x59, 0xb7,
	0x00, 0xc5, 0x60, 0xb2, 0x5f, 0x8b, 0x9a, 0x14, 0xc3, 0x25, 0x8b, 0x2c, 0x4b, 0x74, 0x02, 0x75,
	0x8f, 0x52, 0x52, 0xa3, 0xdd, 0x29, 0x65, 0xe9, 0x48, 0xc4, 0x1a, 0x42, 0x53, 0xcd, 0xe3, 0x8f,
	0xc3, 0x1d, 0x40, 0x63, 0x1c, 0x05, 0xb4, 0x58, 0x32, 0x31, 0x75, 0xb3, 0x3e, 0x69, 0x00, 0x0f,
	0xc5, 0x70, 0x56, 0xf5, 0xf7, 0x04, 0x8c, 0x34, 0x47, 0x2e, 0x8a, 0xb9, 0xbd, 0x08, 0x8e, 0x80,
	0x88, 0x32, 0x23, 0x8a, 0x5e, 0x49, 0x21, 0x88, 0x9d, 0xbf, 0x1a, 0x65, 0xe3, 0x7b, 0x51, 0x25,
	0xd8, 0xba, 0x84, 0x86, 0xdc, 0x1d, 0x4a, 0x88, 0x7a, 0xaf, 0x7a, 0x2c, 0xce, 0xec, 0x18, 0xda,
	0x9b, 0xb6, 0x28, 0x39, 0x85, 0xc1, 0xfa, 0xa2, 0x41, 0x53, 0xad, 0x52, 0xa5, 0x9c, 0x73, 0x30,
	0x16, 0x85, 0x9c, 0x5f, 0x5e, 0xed, 0x9e, 0xfd, 0x90, 0x23, 0x97, 0x9d, 0x17, 0x24, 0x12, 0xf6,
	0x22, 0x85, 0x69, 0x15, 0xc2, 0x5e, 0x24, 0x45, 0x35, 0xca, 0x78, 0xab, 0x51, 0x87, 0xd7, 0xd0,
	0xde, 0x04, 0xae, 0x98, 0x19, 0xab, 0x3c, 0x33, 0x5b, 0x8f, 0x47, 0x79, 0x82, 0xee, 0x01, 0x8a,
	0xad, 0xaf, 0xd8, 0xaa, 0x37, 0x7a, 0xfc, 0xba, 0x5e, 0xfa, 0x76, 0xbd, 0xee, 0xa1, 0x2e, 0x1e,
	0x87, 0x42, 0x88, 0xf6, 0x96, 0x10, 0xd6, 0x2b, 0xbd, 0x5d, 0xb5, 0x8a, 0xb7, 0x6b, 0xf3, 0x72,
	0x0d, 0x3d, 0x38, 0x4b, 0xb2, 0xc0, 0x0e, 0x57, 0x29, 0x66, 0x13, 0x1c, 0x07, 0x98, 0xd9, 0x4f,
	0xae, 0x97, 0x45, 0xbe, 0xfc, 0x7f, 0xe4, 0xb6, 0xfa, 0xbb, 0x08, 0xf7, 0x0f, 0x7f, 0x06, 0x11,
	0x0f, 0xe7, 0x9e, 0xed, 0x27, 0xd3, 0x7e, 0xc9, 0xa5, 0x2f, 0x5d, 0x2e, 0xa4, 0xcb, 0x45, 0x90,
	0xf4, 0xcb, 0xff, 0x24, 0xaf, 0x21, 0xec, 0x7f, 0x7c, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x95,
	0x26, 0x31, 0xaa, 0x06, 0x00, 0x00,
}
